### PR TITLE
WIP: get_all_users() API

### PR DESCRIPTION
**Pull request by polachok**
This is totally unsafe because setpwent() / endpwent() modify global state.
It's only safe to have one instance of this iterator in a process.
I don't know how to make it safe, that's the reason for WIP.

### CODE REVIEW

**Comment by ogham** [comment]
Hey there - sorry for the late reply, and thanks for taking a crack at this. :+1:

I’m not surprised that you ran into difficulties integrating it into rust-users, though, as when I designed the API, I wasn’t thinking about this particular use case, and it’s hard to work with as a result!

The original users code was split off from exa’s users code. This code only had to do one thing, which was to check whether we’d already loaded a user, and if we hadn’t, then load one and return its details. So the only method took `&mut self`, and you were meant to start with an empty users cache.

Since then, I’ve seen cases where it’s better to start with a list of _all_ the users, which doesn’t really fit in its API, because if you know you’re _never_ going to add a user, you don’t need to use `&mut self` instead of `&self`.

I actually fell victim to this the other day when trying to make exa load files in parallel - I had to put the `Users` value in a `Mutex` because all of its methods took `&mut self`, even when I know there was no chance it could be modified!

Anyway. It’s super annoying that `getpwent`/`setpwent`/`endpwent` modify global state. This may have made sense when we were using resource-constrained C, but now it’s just dangerous! The only solution that I can think of is to instead of returning an iterator, instead read in all the users into a `Users` object, then return that object and iterate over _that_. I think this would be the only way to properly hide the fact that those functions are modifying a global state. You do mention that we could use a `Mutex`, but wouldn’t that only be used when two separate threads are modifying the _same_ iterator, rather than two different iterators? (I’m not sure)

**Comment by polachok** [comment]
> The only solution that I can think of is to instead of returning an iterator, instead read in all the users into a Users object, then return that object and iterate over that. 

Do you mean an API like `OSUsers::all_users() -> OSUsers` + `OSUsers::iter() -> Iterator<User>`?
We still have to make sure that some other thread doesn't interfere with us while we're reading.
I'm thinking 'static + Mutex here (is that possible?)

**Comment by ogham** [comment]
> Do you mean an API like `OSUsers::all_users() -> OSUsers` + `OSUsers::iter() -> Iterator<User>`?

Yes, something like that. You’d have to collect all the users up front, and then iterate them over later. However:

> We still have to make sure that some other thread doesn't interfere with us while we're reading.
> I'm thinking 'static + Mutex here (is that possible?)

Good point—I didn’t think of that. Even if we could limit the places that users of the library could get a complete list of all OS users, there’d be nothing to stop them from just calling `getpwent` elsewhere! The [Linux man page for getpwent](http://man7.org/linux/man-pages/man3/getpwent.3.html#ATTRIBUTES) says that it’s not thread-safe. Is the only way to do this to have the `all_users` function marked `unsafe`? Because that sucks.

**Comment by polachok** [comment]
> The Linux man page for getpwent says that it’s not thread-safe.

True, even the _r version is not thread safe.
http://man7.org/linux/man-pages/man3/getpwent_r.3.html#ATTRIBUTES

> Is the only way to do this to have the all_users function marked unsafe? Because that sucks.

Yes, I think so. We can't really defend against a setpwent() / getpwent() "attack" done by some other thread / FFI call.

**Comment by ogham** [comment]
I eventually got around to reworking the library so it doesn't take `&mut self`, and after that, I was able to merge this PR... completely sidestepping the safety issue by marking everything that iterates over all users as `unsafe`! That technically solves the problem by putting the burden on the user instead, but per our previous discussion I think it's the best we can do.

**Pull request merged**
